#include "BlackjackHUD.h"
#include "BlackjackGameMode.h"
#include "PlayerActor.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Components/Image.h"
#include "Kismet/GameplayStatics.h"

void UBlackjackHUD::NativeConstruct()
{
    Super::NativeConstruct();

    // âœ… ë²„íŠ¼ í´ë¦­ ì´ë²¤íŠ¸ ë°”ì¸ë”©
    if (BTN_Hit) BTN_Hit->OnClicked.AddDynamic(this, &UBlackjackHUD::OnHitClicked);
    if (BTN_Stand) BTN_Stand->OnClicked.AddDynamic(this, &UBlackjackHUD::OnStandClicked);
    if (BTN_Split) BTN_Split->OnClicked.AddDynamic(this, &UBlackjackHUD::OnSplitClicked);
    if (BTN_Bet10) BTN_Bet10->OnClicked.AddDynamic(this, &UBlackjackHUD::OnBet10Clicked);
    if (BTN_Bet50) BTN_Bet50->OnClicked.AddDynamic(this, &UBlackjackHUD::OnBet50Clicked);
    if (BTN_Bet100) BTN_Bet100->OnClicked.AddDynamic(this, &UBlackjackHUD::OnBet100Clicked);
    if (BTN_BetMax) BTN_BetMax->OnClicked.AddDynamic(this, &UBlackjackHUD::OnBetMaxClicked);
    if (BTN_Bet) BTN_Bet->OnClicked.AddDynamic(this, &UBlackjackHUD::OnBetClicked);

    // âœ… ê²Œìž„ ëª¨ë“œ ê°€ì ¸ì˜¤ê¸°
    GameMode = Cast<ABlackjackGameMode>(UGameplayStatics::GetGameMode(GetWorld()));
   
    UpdateMessageText("Place Your Bets!", 120.0f);

    // ðŸ”¹ A ì„ íƒ ë²„íŠ¼ ë°”ì¸ë”©
    if (BTN_AceAsOne) BTN_AceAsOne->OnClicked.AddDynamic(this, &UBlackjackHUD::OnAceAsOneClicked);
    if (BTN_AceAsEleven) BTN_AceAsEleven->OnClicked.AddDynamic(this, &UBlackjackHUD::OnAceAsElevenClicked);

    // A ì„ íƒ ë²„íŠ¼ì€ ê¸°ë³¸ì ìœ¼ë¡œ ìˆ¨ê¹€
    HideAceChoice();
}

  // Add this include at the top of the file

void UBlackjackHUD::ShowAceChoice()
{
    /*BTN_AceAsOne->SetVisibility(ESlateVisibility::Visible);
    BTN_AceAsEleven->SetVisibility(ESlateVisibility::Visible);
    Ace_Image->SetVisibility(ESlateVisibility::Visible);*/

    BTN_AceAsOne->SetIsEnabled(true);
    BTN_AceAsEleven->SetIsEnabled(true);
    Ace_Image->SetIsEnabled(true);

    // ðŸŽ² A ì„ íƒí•˜ëŠ” ë™ì•ˆ ë‹¤ë¥¸ ë²„íŠ¼ ë¹„í™œì„±í™”
    SetActionButtonsEnabled(false);

    UE_LOG(LogTemp, Warning, TEXT("A ì„ íƒì§€ í™œì„±í™”"));
}

void UBlackjackHUD::HideAceChoice()
{
    /*BTN_AceAsOne->SetVisibility(ESlateVisibility::Hidden);
    BTN_AceAsEleven->SetVisibility(ESlateVisibility::Hidden);
    Ace_Image->SetVisibility(ESlateVisibility::Hidden);*/

    BTN_AceAsOne->SetIsEnabled(false);
    BTN_AceAsEleven->SetIsEnabled(false);
    Ace_Image->SetIsEnabled(false);

    // ðŸŽ² ì„ íƒ í›„ ì•¡ì…˜ ë²„íŠ¼ ë‹¤ì‹œ í™œì„±í™”
    SetActionButtonsEnabled(true);

    UE_LOG(LogTemp, Warning, TEXT("A ì„ íƒì§€ ë¹„í™œì„±í™”"));
}

void UBlackjackHUD::UpdateScores(const FString& PlayerScore, const FString& DealerScore)
{
    if (TXT_PlayerScore)
    {
        TXT_PlayerScore->SetText(FText::FromString(PlayerScore));
    }

    if (TXT_DealerScore)
    {
        TXT_DealerScore->SetText(FText::FromString(DealerScore));
    }
}




void UBlackjackHUD::UpdatePlayerInfo(int32 PlayerCoins, int32 CurrentBet)
{
    if (TXT_PlayerCoins)
    {
        TXT_PlayerCoins->SetText(FText::FromString(FString::Printf(TEXT("%d"), PlayerCoins)));
    }

    if (TXT_BetAmount)
    {
        TXT_BetAmount->SetText(FText::FromString(FString::Printf(TEXT("%d"), CurrentBet)));
    }
}

void UBlackjackHUD::UpdateMessageText(const FString& NewMessage, float TextSize)
{
    if (TXT_Message)
    {
        TXT_Message->SetText(FText::FromString(NewMessage));

        // âœ… í…ìŠ¤íŠ¸ í¬ê¸° ì„¤ì •
        TXT_Message->SetRenderScale(FVector2D(TextSize / 250.0f, TextSize / 250.0f));

        // âœ… ë©”ì‹œì§€ê°€ ë³€ê²½ë˜ì—ˆì„ ë•Œë§Œ í‘œì‹œ
        TXT_Message->SetVisibility(ESlateVisibility::Visible);
    }
}

void UBlackjackHUD::InitializeUI(int32 StartingCoins)
{
    if (TXT_PlayerCoins)
    {
        TXT_PlayerCoins->SetText(FText::FromString(FString::Printf(TEXT("%d"), StartingCoins)));
    }

    if (TXT_BetAmount)
    {
        TXT_BetAmount->SetText(FText::FromString(TEXT("0")));  // ì´ˆê¸° ë² íŒ… ê¸ˆì•¡ 0
    }

    // ðŸŽ² ì´ˆê¸°ì—ëŠ” ë² íŒ… ë²„íŠ¼ë§Œ í™œì„±í™”, ì•¡ì…˜ ë²„íŠ¼ ë¹„í™œì„±í™”
    SetActionButtonsEnabled(false);
    SetBetButtonsEnabled(true);
}

void UBlackjackHUD::SetActionButtonsEnabled(bool bEnabled)
{
    if (BTN_Hit) BTN_Hit->SetIsEnabled(bEnabled);
    if (BTN_Stand) BTN_Stand->SetIsEnabled(bEnabled);
    if (BTN_Split) BTN_Split->SetIsEnabled(bEnabled);
}

void UBlackjackHUD::SetBetButtonsEnabled(bool bEnabled)
{
    BTN_Bet10->SetIsEnabled(bEnabled);
    BTN_Bet50->SetIsEnabled(bEnabled);
    BTN_Bet100->SetIsEnabled(bEnabled);
    BTN_BetMax->SetIsEnabled(bEnabled);
    BTN_Bet->SetIsEnabled(bEnabled);
}

void UBlackjackHUD::NextGame()
{
    if (GameMode)
    {
        GameMode->ResetForNextRound();
    }
}

void UBlackjackHUD::OnHitClicked()
{
    
    if (GameMode)
    {
        GameMode->PlayerHit();
    }
}

void UBlackjackHUD::OnStandClicked()
{
    
    if (GameMode)
    {
        GameMode->PlayerStand();
    }
}

void UBlackjackHUD::OnSplitClicked()
{
    
    if (GameMode)
    {
        GameMode->PlayerSplit();  // âœ… ë‹¤ì‹œ í˜¸ì¶œ ê°€ëŠ¥í•˜ë„ë¡ ìˆ˜ì •ë¨
    }
}

void UBlackjackHUD::OnBet10Clicked()
{
    if (GameMode && GameMode->Player)
    {
        if (GameMode->Player->PlaceBet(10)) // ðŸŽ² 10 ì½”ì¸ ë°°íŒ…
        {
            UpdatePlayerInfo(GameMode->Player->Coins, GameMode->Player->CurrentBet);
        }
    }
}

void UBlackjackHUD::OnBet50Clicked()
{
    if (GameMode && GameMode->Player)
    {
        if (GameMode->Player->PlaceBet(50)) // ðŸŽ² 50 ì½”ì¸ ë°°íŒ…
        {
            UpdatePlayerInfo(GameMode->Player->Coins, GameMode->Player->CurrentBet);
        }
    }
}

void UBlackjackHUD::OnBet100Clicked()
{
    if (GameMode && GameMode->Player)
    {
        if (GameMode->Player->PlaceBet(100)) // ðŸŽ² 100 ì½”ì¸ ë°°íŒ…
        {
            UpdatePlayerInfo(GameMode->Player->Coins, GameMode->Player->CurrentBet);
        }
    }
}

void UBlackjackHUD::OnBetMaxClicked()
{
    if (GameMode && GameMode->Player)
    {
        if (GameMode->Player->PlaceBet(GameMode->Player->Coins)) // ðŸŽ² ìµœëŒ€ ì½”ì¸ ë°°íŒ…
        {
            UpdatePlayerInfo(GameMode->Player->Coins, GameMode->Player->CurrentBet);
        }
    }
}


void UBlackjackHUD::OnBetClicked()
{
    TXT_Message->SetVisibility(ESlateVisibility::Hidden);
    if (GameMode)
    {
        GameMode->ConfirmBet(); // ðŸŸ¢ "ë² íŒ… ì™„ë£Œ" ì²˜ë¦¬
        GameMode->StartGame();
    }
}

void UBlackjackHUD::OnAceAsOneClicked()
{
    GameMode = Cast<ABlackjackGameMode>(UGameplayStatics::GetGameMode(GetWorld()));
    if (GameMode)
    {
        GameMode->HandleAceChoice(1);
    }
}

void UBlackjackHUD::OnAceAsElevenClicked()
{
    GameMode = Cast<ABlackjackGameMode>(UGameplayStatics::GetGameMode(GetWorld()));
    if (GameMode)
    {
        GameMode->HandleAceChoice(11);
    }
}