#include "CardActor.h"

ACardActor::ACardActor()
{
    PrimaryActorTick.bCanEverTick = false;

    // ğŸ´ ì¹´ë“œ ë©”ì‹œ ìƒì„±
    CardMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("CardMesh"));
    RootComponent = CardMesh;

    // ê¸°ë³¸ ë¨¸í‹°ë¦¬ì–¼ ì„¤ì •
    FaceMaterial = nullptr;
    BackMaterial = nullptr;

    // ê¸°ë³¸ ì¹´ë“œ ì„¤ì • (ì˜ˆ: í•˜íŠ¸ A)
    Suit = ESuit::Hearts;
    Rank = ERank::Ace;
}

void ACardActor::BeginPlay()
{
    Super::BeginPlay();

    if (FaceMaterial)
    {
        MID = UMaterialInstanceDynamic::Create(FaceMaterial, this);
        if (MID)
        {
            CardMesh->SetMaterial(0, MID);
            UE_LOG(LogTemp, Warning, TEXT("BeginPlay(): DynamicMaterialInstance created and applied to CardMesh."));

            // âœ… ê°•ì œë¡œ ë Œë”ë§ ì—…ë°ì´íŠ¸ ì¶”ê°€
            //CardMesh->MarkRenderStateDirty();
        }
    }
}





// ğŸ”¹ ì¹´ë“œ ì •ë³´ ì„¤ì • (ë¬¸ì–‘ & ìˆ«ì)
void ACardActor::SetCard(ESuit NewSuit, ERank NewRank)
{
    UE_LOG(LogTemp, Warning, TEXT("SetCard(): Called with Suit=%d, Rank=%d"), static_cast<int32>(NewSuit), static_cast<int32>(NewRank));

    Suit = NewSuit;
    Rank = NewRank;

    int32 TextureIndex = GetTextureIndex(Suit, Rank);
    FString TexturePath = FString::Printf(TEXT("/Game/Textures/Cards/T_Card_%d"), TextureIndex);

    UTexture2D* CardTexture = LoadObject<UTexture2D>(nullptr, *TexturePath);
    /*if (!CardTexture)
    {
        UE_LOG(LogTemp, Error, TEXT("SetCard(): Failed to load texture: %s"), *TexturePath);
        return;
    }*/

    // âœ… DMIê°€ ì—†ìœ¼ë©´ ìƒˆë¡œ ìƒì„±
    /*if (!MID && FaceMaterial)
    {
        MID = UMaterialInstanceDynamic::Create(FaceMaterial, this);
        CardMesh->SetMaterial(0, MID);
        UE_LOG(LogTemp, Warning, TEXT("SetCard(): Created new DynamicMaterialInstance"));
    }*/

    if (MID)
    {
        // âœ… í…ìŠ¤ì²˜ ì ìš©
        MID->SetTextureParameterValue(TEXT("Card_Image"), CardTexture);
        //CardMesh->MarkRenderStateDirty();  // âœ… ë Œë”ë§ ìƒíƒœ ì—…ë°ì´íŠ¸

        UE_LOG(LogTemp, Warning, TEXT("SetCard(): Applied Texture = %s"), *TexturePath);

        // ğŸš¨ **ì‹¤ì œ ì ìš©ëœ í…ìŠ¤ì²˜ë¥¼ í™•ì¸í•˜ëŠ” ë””ë²„ê¹… ì½”ë“œ ì¶”ê°€**
    /*    UTexture* AppliedTexture = nullptr;
        if (MID->GetTextureParameterValue(FName("Card_Image"), AppliedTexture))
        {
            if (AppliedTexture)
            {
                UE_LOG(LogTemp, Warning, TEXT("SetCard(): Confirmed Applied Texture = %s"), *AppliedTexture->GetName());
            }
            else
            {
                UE_LOG(LogTemp, Error, TEXT("SetCard(): AppliedTexture is NULL after setting!"));
            }
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("SetCard(): Failed to get texture parameter value!"));
        }*/
    }

    //UE_LOG(LogTemp, Warning, TEXT("SetCard(): Applying Dynamic Material Instance..."));
    CardMesh->SetMaterial(0, MID);

    //// ğŸš¨ ì ìš©ëœ ë¨¸í‹°ë¦¬ì–¼ í™•ì¸
    //UMaterialInterface* CurrentMat = CardMesh->GetMaterial(0);
    //if (CurrentMat)
    //{
    //    UE_LOG(LogTemp, Warning, TEXT("SetCard(): Current Material After Set = %s"), *CurrentMat->GetName());
    //}
    //else
    //{
    //    UE_LOG(LogTemp, Error, TEXT("SetCard(): Failed to retrieve material from CardMesh!"));
    //}


    /*UTexture* AppliedTexture;
    if (MID->GetTextureParameterValue(FName("Card_Image"), AppliedTexture))
    {
        if (AppliedTexture)
        {
            UE_LOG(LogTemp, Warning, TEXT("SetCard(): Confirmed Applied Texture (After Set) = %s"), *AppliedTexture->GetName());
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("SetCard(): Applied Texture is NULL after SetTextureParameterValue!"));
        }
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("SetCard(): GetTextureParameterValue failed for Card_Image"));
    }*/

}




// ğŸ”¹ í…ìŠ¤ì²˜ ì¸ë±ìŠ¤ ê³„ì‚° í•¨ìˆ˜ (0~51 ë²”ìœ„)
int32 ACardActor::GetTextureIndex(ESuit InSuit, ERank InRank)
{

    return (static_cast<int32>(InSuit) * 13) + static_cast<int32>(InRank);
}

void ACardActor::SetCardTexture(UTexture2D* NewTexture)
{
    if (!NewTexture)
    {
        UE_LOG(LogTemp, Error, TEXT("SetCardTexture(): NewTexture is NULL!"));
        return;
    }

    if (!MID)
    {
        UE_LOG(LogTemp, Error, TEXT("SetCardTexture(): DynamicMaterialInstance is NULL!"));
        return;
    }

    // âœ… ë³€ê²½ ì „ í˜„ì¬ í…ìŠ¤ì²˜ í™•ì¸
    UTexture* CurrentTexture = nullptr;
    MID->GetTextureParameterValue(FName("Card_Image"), CurrentTexture);
    UE_LOG(LogTemp, Warning, TEXT("SetCardTexture(): Current Texture Before Change = %s"), *GetNameSafe(CurrentTexture));

    // âœ… ìƒˆë¡œìš´ í…ìŠ¤ì²˜ ì ìš©
    MID->SetTextureParameterValue(TEXT("Card_Image"), NewTexture);
    CardMesh->MarkRenderStateDirty();  // âœ… ë Œë”ë§ ê°•ì œ ì—…ë°ì´íŠ¸

    // âœ… ì ìš© í›„ í…ìŠ¤ì²˜ í™•ì¸
    MID->GetTextureParameterValue(FName("Card_Image"), CurrentTexture);
    UE_LOG(LogTemp, Warning, TEXT("SetCardTexture(): Current Texture After Change = %s"), *GetNameSafe(CurrentTexture));

    UE_LOG(LogTemp, Warning, TEXT("SetCardTexture(): Texture applied successfully! NewTexture = %s"), *GetNameSafe(NewTexture));
}






// ğŸ”„ ì¹´ë“œ ì•/ë’·ë©´ ì„¤ì • í•¨ìˆ˜
void ACardActor::SetFaceUp(bool bIsFaceUp)
{
    if (bIsFaceUp && FaceMaterial)
    {
        CardMesh->SetMaterial(0, FaceMaterial);
    }
    else if (!bIsFaceUp && BackMaterial)
    {
        CardMesh->SetMaterial(0, BackMaterial);
    }
}
